_BASE_: "../Base_faster_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.05
    # todo: later I would need parameters for each head seperately, like optimizer, lr, whether all classes anchors and things are used or only part of them, the loss function of the detection head (focal loss)
#todo gambler architecture
  GAMBLER_HEAD:
    NAME: "SimpleGambler"
    GAMBLER_OUTPUT: "C"
DATASETS:
  TRAIN: ("coco_2017_train_100samples",)
  TEST: ("coco_2017_train_100samples",)
TEST:
    EVAL_PERIOD: 250
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (3500, 4500)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 250
OUTPUT_DIR: "./output/debug_gambler"