_BASE_: "./simple_retinanet.yaml"
MODEL:
  WEIGHTS: "./output/retinanet_baselines/simple_retina_overfit/1gpu_scale64_p4_lr2/model_final.pth"
SOLVER:
  BASE_LR: 0.0001
OUTPUT_DIR: "./output/gambler/fix_retina_lre4"