_BASE_: "./simple_retinanet.yaml"
MODEL:
  WEIGHTS: "./output/retinanet_baselines/simple_retina_overfit/p4_3scales/model_final.pth" #todo change to all scales all aspect ratios
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x * 2**(-5.0/6), x * 2**(-4.0/6), x * 2**(-3.0/6), x * 2**(-2.0/6), x * 2**(-1.0/6), x, x * 2**(1.0/6), x * 2**(2.0/6), x * 2**(3.0/6), x * 2**(4.0/6), x * 2**(5.0/6)] for x in [128]]"] #multiple scales
    ASPECT_RATIOS: [[1.0]]  # 1 aspect ratio
TEST:
    EVAL_PERIOD: 2250
SOLVER:
  STEPS: (30000, 40000)
  MAX_ITER: 45000
  CHECKPOINT_PERIOD: 2250
OUTPUT_DIR: "./output/gambler/11scales_1weight"