_BASE_: "./simple_retinanet.yaml"
MODEL:
  WEIGHTS: "./output/retinanet_baselines/simple_retina_overfit/1gpu_scale64_p4_lr2/model_final.pth" #todo change to all scales all aspect ratios
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"] #multiple scales
    ASPECT_RATIOS: [[1.0]]  # 1 aspect ratio
OUTPUT_DIR: "./output/gambler/debug"