_BASE_: "./simple_retinanet.yaml"
MODEL:
#  WEIGHTS: "./output/retinanet_baselines/simple_retinanet/simple_retina_overfit/p4_128_11scales/model_final.pth" #todo change to all scales all aspect ratios
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0]]  # 1 aspect ratio
DATASETS:
  TRAIN: ("coco_2017_train_100samples",)
  TEST: ("coco_2017_train_100samples",)
TEST:
    EVAL_PERIOD: 1
SOLVER:
  STEPS: (43000,)
  MAX_ITER: 45000
  CHECKPOINT_PERIOD: 2250
#INPUT:
#  MIN_SIZE_TRAIN: (640, )
#  RANDOM_FLIPPING: False
OUTPUT_DIR: "./output/gambler/debug"