_BASE_: "./simple_retinanet.yaml"
SEED: 57330821
MODEL:
#  WEIGHTS: "./output/gambler/11scales_fix_detector_no_temperature_lambda27500/model_final.pth"
#  WEIGHTS: "./output/retinanet_baselines/simple_retinanet/simple_retina_overfit/p4_128_11scales/model_final.pth"
#  WEIGHTS: "./output/gambler/Detector_only/model_0000999.pth"
  WEIGHTS: "./output/retinanet_baselines/simple_retinanet/simple_retina_overfit/p4_3scales/model_final.pth"
#  ANCHOR_GENERATOR:
#    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3)] for x in [64]]"]
  RETINANET:
    NUM_CLASSES: 80 #1230
  ROI_HEADS:
    NUM_CLASSES: 80 #1230
  GAMBLER_HEAD:
    NAME: "LayeredUnetGambler"
    GAMBLER_ITERATIONS: 100
    DETECTOR_ITERATIONS: 0
    GAMBLER_OUTPUT: "L_BCAHW" #"B1HW"
    GAMBLER_LAMBDA: 1 # GAMBLER_OUT_CHANNELS*w=28*h=40 #todo: need to change to actual h and w times scales
    GAMBLER_OUTSIDE_LAMBDA: 1
    GAMBLER_TEMPERATURE: 1e-20 #1e-20 epsilon is needed for divide by 0
    GAMBLER_LOSS_MODE: "focal"
    GAMBLER_OUT_CHANNELS: 240
    GAMBLER_IN_CHANNELS: 240 #3*80+3
    BASE_LR: 0.001
    NORMALIZE: True
    BILINEAR_UPSAMPLING: False
    NUM_CLASSES: 80 #1230
    IN_LAYERS: [80, 40, 20, 10, 5]
#    GAMBLER_IN_LAYERS: 5
#    GAMBLER_OUT_LAYERS: 5
#    IMAGE_MODE: "conv"
#    IMAGE_CHANNELS: 3
#    FIXED_CHANNEL: 32
#    DATA_RANGE: [-0.5, 0.5]
#    LOAD_PRETRAINED_GAMBLER: True
#    WEIGHTS: "./output/gambler/11scales_fix_detector_no_temperature_lambda27500/gambler_models/model_final.pth"
DATASETS:
#  TRAIN: ("coco_2017_train_8samples",)
#  TEST: ("coco_2017_train_8samples",)
#  TRAIN: ("coco_2017_train_8_difficult_samples",)
#  TEST: ("coco_2017_train_8_difficult_samples",)
  TRAIN: ("coco_2017_train_100samples",)
  TEST: ("coco_2017_train_100samples",)
TEST:
  EVAL_PERIOD: 1000 #500
SOLVER:
  STEPS: (8000,8500)
  MAX_ITER: 9000
  CHECKPOINT_PERIOD: 9000
INPUT:
  MAX_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: (640, )
  RANDOM_FLIPPING: False
  RESIZING: False
DATALOADER:
    ASPECT_RATIO_GROUPING: False
OUTPUT_DIR: "./output/gambler/debug"