_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 80 #1230
#    SCORE_THRESH_TEST: 0.0001
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x] for x in [ 32 ]]"] # 1 scale (hopefully in the biggest feature map)
    ASPECT_RATIOS: [[1.0]]  # 1 aspect ratio
  RETINANET:
    NUM_CLASSES: 80
    IN_FEATURES: ["p3"] # 1 feature map layer - p3 is stride 8 - original retinanet ["p3", "p4", "p5", "p6", "p7"]
  GAMBLER_HEAD:
    NAME: "SimpleGambler"
    GAMBLER_OUTPUT: "C"
DATASETS:
  TRAIN: ("coco_2017_train_100samples",)
  TEST: ("coco_2017_train_100samples",)
#TEST:
#  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
TEST:
    EVAL_PERIOD: 250
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (3500, 4500)
  MAX_ITER: 5000
#  CHECKPOINT_PERIOD: 250
OUTPUT_DIR: "./output/retinanet_baselines/debug_debug_debug"