#debugging but will change to full coco dataset
_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_train_100samples",)
  TEST: ("coco_2017_train_100samples",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (20000, 25000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 1500
TEST:
  EVAL_PERIOD: 1500
OUTPUT_DIR: "./output/retinanet_baselines/debug_retinanet/"
