_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
#INPUT:
#  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train_one_forth",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#  EVAL_PERIOD: 300 # Evaluate the AP every EVAL_PERIOD
#DATALOADER:
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.001
<<<<<<< HEAD:configs/LVIS-ImbalanceDetection/faster_rcnn_R_50_FPN_1x.yaml
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (7500, 10000)
  MAX_ITER: 11300
  CHECKPOINT_PERIOD: 570
OUTPUT_DIR: "./output/sampled_img16__11k_2gpus"
=======
OUTPUT_DIR: "./output/fasterrcnn_baselines"
>>>>>>> master:configs/LVIS-ImbalanceDetection/faster_rcnn_R_50_FPN_1x.yaml
