_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "FasterRCNNFocalLoss"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
#    NUM_CLASSES: 1230
    SCORE_THRESH_TEST: 0.0001
#    BATCH_SIZE_PER_IMAGE: 1
#  RPN:
#    BATCH_SIZE_PER_IMAGE: 1
  RETINANET:
      FOCAL_LOSS_ALPHA: 1.0
      FOCAL_LOSS_GAMMA: 2.0
      PRIOR_PROB: 0.5
#INPUT:
#  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
#DATASETS:
#  TRAIN: ("lvis_v0.5_train_one_forth",)
#  TEST: ("lvis_v0.5_val",)
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
TEST:
#  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
  EVAL_PERIOD: 4500 # Evaluate the AP every EVAL_PERIOD
#DATALOADER:
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.001
SOLVER:
  IMS_PER_BATCH: 8
#  BASE_LR: 0.02
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000 # Note that full coco dataset needs 90k iterations to converge
  CHECKPOINT_PERIOD: 4500
OUTPUT_DIR: "./output/faster_focal/faster_focal_gamma2_alpha1_coco_smoothl1_pi5"
